### ISSUE TITLE
Homepage is unreachable

### ISSUE THREAD

**Issue by ilovezfs** [tmiw/kite-llvm#2]
http://www.kite-language.org/ is returning 502 Bad Gateway

**Comment by tmiw** [comment]
Fixed. Sorry about that!

**Comment by ilovezfs** [comment]
Thanks!

**Comment by ilovezfs** [comment]
@tmiw it looks like it's returning 502 again

**Comment by tmiw** [comment]
Oops, fixed. This time I believe I tweaked the configuration for php5-fpm so that this doesn't happen again.

**Comment by ilovezfs** [comment]
Thanks!
